import AppProvider from "@/app/providers/app-provider";
import Footer from "@/components/footer/footer";
import { geistMono, geistSans } from "@/app/theme/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Philtech Website Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body>
        <AppProvider>
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
